var product = [
  {
    id: 0,
    name: "",
    brand: "",
    price: "",
    color: [],
    image: "",
    display_size: "",
    display_type: "",
    os: "",
    chipset: "",
    memory: [],
    main_camera: "",
    front_camera: "",
    battery: "",
  },

  {
    id: 1,
    name: "iPhone 8",
    brand: "Apple",
    price: "Starting at $699",
    color: ["Silver", "Space Gray", "Gold"],
    image: "",
    display_size: "4.7 inches",
    display_type: "Retina HD display",
    os: "iOS 14 (upgradable)",
    chipset: "Apple A11 Bionic",
    memory: ["64GB", "128GB"],
    main_camera: "12 MP, f/1.8, 28mm (wide), OIS",
    front_camera: "7 MP, f/2.2, 32mm (standard)",
    battery: "Built-in rechargeable lithium-ion battery",
  },
  {
    id: 2,
    name: "iPhone X",
    brand: "Apple",
    price: "Starting at $999",
    color: ["Space Gray", "Silver"],
    image: "",
    display_size: "5.8 inches",
    display_type: "Super Retina OLED display",
    os: "iOS 14 (upgradable)",
    chipset: "Apple A11 Bionic",
    memory: ["64GB", "256GB"],
    main_camera:
      "Dual 12 MP, f/1.8, 28mm (wide), OIS + 12 MP, f/2.4, 52mm (telephoto), OIS",
    front_camera: "7 MP, f/2.2, 32mm (standard)",
    battery: "Built-in rechargeable lithium-ion battery",
  },
  {
    id: 3,
    name: "iPhone XR",
    brand: "Apple",
    price: "Starting at $749",
    color: ["White", "Black", "Blue", "Yellow", "Coral", "(PRODUCT)RED"],
    image: "",
    display_size: "6.1 inches",
    display_type: "Liquid Retina IPS LCD display",
    os: "iOS 14 (upgradable)",
    chipset: "Apple A12 Bionic",
    memory: ["64GB", "128GB", "256GB"],
    main_camera: "12 MP, f/1.8, 26mm (wide)",
    front_camera: "7 MP, f/2.2, 32mm (standard)",
    battery: "Built-in rechargeable lithium-ion battery",
  },

  {
    id: 4,
    name: "iPhone XS",
    brand: "Apple",
    price: "Starting at $999",
    color: ["Space Gray", "Silver", "Gold"],
    image: "",
    display_size: "5.8 inches",
    display_type: "Super Retina OLED display",
    os: "iOS 14 (upgradable)",
    chipset: "Apple A12 Bionic",
    memory: ["64GB", "256GB", "512GB"],
    main_camera:
      "Dual 12 MP, f/1.8, 26mm (wide) + 12 MP, f/2.4, 52mm (telephoto)",
    front_camera: "7 MP, f/2.2, 32mm (standard)",
    battery: "Built-in rechargeable lithium-ion battery",
  },

  {
    id: 5,
    name: "iPhone XS Max",
    brand: "Apple",
    price: "Starting at $1099",
    color: ["Space Gray", "Silver", "Gold"],
    image: "",
    display_size: "6.5 inches",
    display_type: "Super Retina OLED display",
    os: "iOS 14 (upgradable)",
    chipset: "Apple A12 Bionic",
    memory: ["64GB", "256GB", "512GB"],
    main_camera:
      "Dual 12 MP, f/1.8, 26mm (wide) + 12 MP, f/2.4, 52mm (telephoto)",
    front_camera: "7 MP, f/2.2, 32mm (standard)",
    battery: "Built-in rechargeable lithium-ion battery",
  },

  {
    id: 6,
    name: "iPhone 11",
    brand: "Apple",
    price: "Starting at $699",
    color: ["Purple", "Yellow", "Green", "Black", "White", "(PRODUCT)RED"],
    image: "",
    display_size: "6.1 inches",
    display_type: "Liquid Retina IPS LCD display",
    os: "iOS 14 (upgradable)",
    chipset: "Apple A13 Bionic",
    memory: ["64GB", "128GB", "256GB"],
    main_camera:
      "Dual 12 MP, f/1.8, 26mm (wide) + 12 MP, f/2.4, 13mm (ultrawide)",
    front_camera: "12 MP, f/2.2, 23mm (wide)",
    battery: "Built-in rechargeable lithium-ion battery",
  },

  {
    id: 7,
    name: "iPhone 11 Pro",
    brand: "Apple",
    price: "Starting at $999",
    color: ["Space Gray", "Silver", "Gold", "Midnight Green"],
    image: "",
    display_size: "5.8 inches",
    display_type: "Super Retina XDR OLED display",
    os: "iOS 14 (upgradable)",
    chipset: "Apple A13 Bionic",
    memory: ["64GB", "256GB", "512GB"],
    main_camera:
      "Triple 12 MP, f/1.8, 26mm (wide) + 12 MP, f/2.0, 52mm (telephoto) + 12 MP, f/2.4, 13mm (ultrawide)",
    front_camera: "12 MP, f/2.2, 23mm (wide)",
    battery: "Built-in rechargeable lithium-ion battery",
  },

  {
    id: 8,
    name: "iPhone 11 Pro Max",
    brand: "Apple",
    price: "Starting at $1099",
    color: ["Space Gray", "Silver", "Gold", "Midnight Green"],
    image: "",
    display_size: "6.5 inches",
    display_type: "Super Retina XDR OLED display",
    os: "iOS 14 (upgradable)",
    chipset: "Apple A13 Bionic",
    memory: ["64GB", "256GB", "512GB"],
    main_camera:
      "Triple 12 MP, f/1.8, 26mm (wide) + 12 MP, f/2.4, 13mm (ultrawide)",
    front_camera: "12 MP, f/2.2, 23mm (wide)",
    battery: "Built-in rechargeable lithium-ion battery",
  },

  {
    id: 9,
    name: "iPhone SE (2nd generation)",
    brand: "Apple",
    price: "Starting at $399",
    color: ["Black", "White", "Red"],
    image: "",
    display_size: "4.7 inches",
    display_type: "Retina IPS LCD display",
    os: "iOS 14 (upgradable)",
    chipset: "Apple A13 Bionic",
    memory: ["64GB", "128GB", "256GB"],
    main_camera: "12 MP, f/1.8, 28mm (wide)",
    front_camera: "7 MP, f/2.2, 32mm (standard)",
    battery: "Built-in rechargeable lithium-ion battery",
  },

  {
    id: 10,
    name: "iPhone 12",
    brand: "Apple",
    price: "Starting at $799",
    color: ["Black", "White", "Red", "Green", "Blue"],
    image: "",
    display_size: "6.1 inches",
    display_type: "Super Retina XDR OLED display",
    os: "iOS 14 (upgradable)",
    chipset: "Apple A14 Bionic",
    memory: ["64GB", "128GB", "256GB"],
    main_camera:
      "Dual 12 MP, f/1.6, 26mm (wide) + 12 MP, f/2.4, 13mm (ultrawide)",
    front_camera: "12 MP, f/2.2, 23mm (wide)",
    battery: "Built-in rechargeable lithium-ion battery",
  },

  {
    id: 11,
    name: "iPhone 12 Mini",
    brand: "Apple",
    price: "Starting at $699",
    color: ["Black", "White", "Red", "Green", "Blue"],
    image: "",
    display_size: "5.4 inches",
    display_type: "Super Retina XDR OLED display",
    os: "iOS 14 (upgradable)",
    chipset: "Apple A14 Bionic",
    memory: ["64GB", "128GB", "256GB"],
    main_camera:
      "Dual 12 MP, f/1.6, 26mm (wide) + 12 MP, f/2.4, 13mm (ultrawide)",
    front_camera: "12 MP, f/2.2, 23mm (wide)",
    battery: "Built-in rechargeable lithium-ion battery",
  },

  {
    id: 12,
    name: "iPhone 12 Pro",
    brand: "Apple",
    price: "Starting at $999",
    color: ["Graphite", "Silver", "Gold", "Pacific Blue"],
    image: "",
    display_size: "6.1 inches",
    display_type: "Super Retina XDR OLED display",
    os: "iOS 14 (upgradable)",
    chipset: "Apple A14 Bionic",
    memory: ["128GB", "256GB", "512GB"],
    main_camera:
      "Triple 12 MP, f/1.6, 26mm (wide) + 12 MP, f/2.4, 52mm (telephoto) + 12 MP, f/2.0, 13mm (ultrawide)",
    front_camera: "12 MP, f/2.2, 23mm (wide)",
    battery: "Built-in rechargeable lithium-ion battery",
  },

  {
    id: 13,
    name: "iPhone 12 Pro Max",
    brand: "Apple",
    price: "Starting at $1099",
    color: ["Graphite", "Silver", "Gold", "Pacific Blue"],
    image: "",
    display_size: "6.7 inches",
    display_type: "Super Retina XDR OLED display",
    os: "iOS 14 (upgradable)",
    chipset: "Apple A14 Bionic",
    memory: ["128GB", "256GB", "512GB"],
    main_camera:
      "Triple 12 MP, f/1.6, 26mm (wide) + 12 MP, f/2.4, 65mm (telephoto) + 12 MP, f/2.2, 13mm (ultrawide)",
    front_camera: "12 MP, f/2.2, 23mm (wide)",
    battery: "Built-in rechargeable lithium-ion battery",
  },

  {
    id: 14,
    name: "iPhone 13",
    brand: "Apple",
    price: "Starting at $799",
    color: ["Pink", "Blue", "Midnight", "Starlight", "Product(RED)"],
    image: "",
    display_size: "6.1 inches",
    display_type: "Super Retina XDR OLED display",
    os: "iOS 15",
    chipset: "Apple A15 Bionic",
    memory: ["128GB", "256GB", "512GB", "1TB"],
    main_camera:
      "Dual 12 MP, f/1.6, 26mm (wide) + 12 MP, f/2.4, 120˚, 13mm (ultrawide)",
    front_camera: "12 MP, f/2.2, 23mm (wide)",
    battery: "Built-in rechargeable lithium-ion battery",
  },

  {
    id: 15,
    name: "iPhone 13 Mini",
    brand: "Apple",
    price: "Starting at $699",
    color: ["Pink", "Blue", "Midnight", "Starlight", "Product(RED)"],
    image: "",
    display_size: "5.4 inches",
    display_type: "Super Retina XDR OLED display",
    os: "iOS 15",
    chipset: "Apple A15 Bionic",
    memory: ["128GB", "256GB", "512GB", "1TB"],
    main_camera:
      "Dual 12 MP, f/1.6, 26mm (wide) + 12 MP, f/2.4, 120˚, 13mm (ultrawide)",
    front_camera: "12 MP, f/2.2, 23mm (wide)",
    battery: "Built-in rechargeable lithium-ion battery",
  },

  {
    id: 16,
    name: "iPhone 13 Pro",
    brand: "Apple",
    price: "Starting at $999",
    color: ["Graphite", "Gold", "Silver", "Sierra Blue"],
    image: "",
    display_size: "6.1 inches",
    display_type: "Super Retina XDR OLED display",
    os: "iOS 15",
    chipset: "Apple A15 Bionic",
    memory: ["128GB", "256GB", "512GB", "1TB"],
    main_camera:
      "Triple 12 MP, f/1.5, 26mm (wide) + 12 MP, f/1.8, 77mm (telephoto) + 12 MP, f/1.8, 120˚, 13mm (ultrawide)",
    front_camera: "12 MP, f/2.2, 23mm (wide)",
    battery: "Built-in rechargeable lithium-ion battery",
  },

  {
    id: 17,
    name: "iPhone 13 Pro",
    brand: "Apple",
    price: "$999",
    color: ["Graphite", "Gold", "Silver", "Sierra Blue"],
    image: "",
    display_size: "6.1 inches",
    display_type: "Super Retina XDR OLED display",
    os: "iOS 15",
    chipset: "Apple A15 Bionic",
    memory: ["128GB", "256GB", "512GB", "1TB"],
    main_camera:
      "Triple 12 MP, f/1.5, 26mm (wide) + 12 MP, f/1.8, 77mm (telephoto) + 12 MP, f/1.8, 120˚, 13mm (ultrawide)",
    front_camera: "12 MP, f/2.2, 23mm (wide)",
    battery: "Built-in rechargeable lithium-ion battery",
  },

  {
    id: 18,
    name: "iPhone 13 Pro Max",
    brand: "Apple",
    price: "$1099",
    color: ["Graphite", "Gold", "Silver", "Sierra Blue"],
    image: "",
    display_size: "6.7 inches",
    display_type: "Super Retina XDR OLED display",
    os: "iOS 15",
    chipset: "Apple A15 Bionic",
    memory: ["128GB", "256GB", "512GB", "1TB"],
    main_camera:
      "Triple 12 MP, f/1.5, 26mm (wide) + 12 MP, f/1.8, 77mm (telephoto) + 12 MP, f/1.8, 120˚, 13mm (ultrawide)",
    front_camera: "12 MP, f/2.2, 23mm (wide)",
    battery: "Built-in rechargeable lithium-ion battery",
  },

  {
    id: 19,
    name: "iPhone 14 Pro",
    brand: "Apple",
    price: "$1199",
    color: ["Graphite", "Gold", "Silver", "Pacific Blue"],
    image: "",
    display_size: "6.1 inches",
    display_type: "Super Retina XDR OLED display",
    os: "iOS 16",
    chipset: "Apple A16 Bionic",
    memory: ["128GB", "256GB", "512GB", "1TB"],
    main_camera:
      "Triple 12 MP, f/1.5, 26mm (wide) + 12 MP, f/1.8, 77mm (telephoto) + 12 MP, f/1.8, 120˚, 13mm (ultrawide)",
    front_camera: "12 MP, f/2.2, 23mm (wide)",
    battery: "Built-in rechargeable lithium-ion battery",
  },

  {
    id: 20,
    name: "iPhone 14 Pro Max",
    brand: "Apple",
    price: "$1299",
    color: ["Graphite", "Gold", "Silver", "Pacific Blue"],
    image: "",
    display_size: "6.7 inches",
    display_type: "Super Retina XDR OLED display",
    os: "iOS 16",
    chipset: "Apple A16 Bionic",
    memory: ["128GB", "256GB", "512GB", "1TB"],
    main_camera:
      "Triple 12 MP, f/1.5, 26mm (wide) + 12 MP, f/1.8, 77mm (telephoto) + 12 MP, f/1.8, 120˚, 13mm (ultrawide)",
    front_camera: "12 MP, f/2.2, 23mm (wide)",
    battery: "Built-in rechargeable lithium-ion battery",
  },
  {
    id: 21,
    name: "Samsung Galaxy S21 Ultra",
    brand: "Samsung",
    price: "$1,199",
    color: ["Phantom Black", "Phantom Silver"],
    image: "",
    display_size: "6.8 inches",
    display_type: "Dynamic AMOLED 2X",
    os: "Android 11",
    chipset: "Exynos 2100 / Qualcomm Snapdragon 888",
    memory: "12GB / 16GB RAM",
    main_camera: "Quad-camera setup",
    front_camera: "40 MP",
    battery: "5,000mAh",
  },
  {
    id: 22,
    name: "Samsung Galaxy Note 20 Ultra",
    brand: "Samsung",
    price: "$1,299",
    color: ["Mystic Bronze", "Mystic Black", "Mystic White"],
    image: "",
    display_size: "6.9 inches",
    display_type: "Dynamic AMOLED 2X",
    os: "Android 10",
    chipset: "Exynos 990 / Qualcomm Snapdragon 865 Plus",
    memory: "12GB RAM",
    main_camera: "Triple-camera setup",
    front_camera: "10 MP",
    battery: "4,500mAh",
  },
  {
    id: 23,
    name: "Samsung Galaxy S20 FE",
    brand: "Samsung",
    price: "$699",
    color: [
      "Cloud Navy",
      "Cloud Lavender",
      "Cloud Mint",
      "Cloud Red",
      "Cloud White",
    ],
    image: "",
    display_size: "6.5 inches",
    display_type: "Super AMOLED",
    os: "Android 10",
    chipset: "Exynos 990 / Qualcomm Snapdragon 865",
    memory: "6GB / 8GB RAM",
    main_camera: "Triple-camera setup",
    front_camera: "32 MP",
    battery: "4,500mAh",
  },
  {
    id: 24,
    name: "Samsung Galaxy A52",
    brand: "Samsung",
    price: "$399",
    color: ["Awesome Black", "Awesome White", "Awesome Blue", "Awesome Violet"],
    image: "",
    display_size: "6.5 inches",
    display_type: "Super AMOLED",
    os: "Android 11",
    chipset: "Qualcomm Snapdragon 720G",
    memory: "4GB / 6GB / 8GB RAM",
    main_camera: "Quad-camera setup",
    front_camera: "32 MP",
    battery: "4,500mAh",
  },
  {
    id: 25,
    name: "Samsung Galaxy A32",
    brand: "Samsung",
    price: "$279",
    color: ["Awesome Black", "Awesome White", "Awesome Blue", "Awesome Violet"],
    image: "",
    display_size: "6.4 inches",
    display_type: "Super AMOLED",
    os: "Android 11",
    chipset: "MediaTek Helio G80",
    memory: "4GB / 6GB / 8GB RAM",
    main_camera: "Quad-camera setup",
    front_camera: "20 MP",
    battery: "5,000mAh",
  },
  {
    id: 26,
    name: "Samsung Galaxy Z Flip",
    brand: "Samsung",
    price: "$1,199",
    color: [
      "Mirror Black",
      "Mirror Purple",
      "Mirror Gold",
      "Thom Browne Edition",
    ],
    image: "",
    display_size: "6.7 inches (foldable)",
    display_type: "Foldable Dynamic AMOLED",
    os: "Android 10",
    chipset: "Qualcomm Snapdragon 855+",
    memory: "8GB RAM",
    main_camera: "Dual-camera setup",
    front_camera: "10 MP",
    battery: "3,300mAh",
  },
  {
    id: 27,
    name: "Samsung Galaxy Z Fold 3",
    brand: "Samsung",
    price: "$1,799",
    color: ["Phantom Black", "Phantom Green", "Phantom Silver"],
    image: "",
    display_size:
      "Main display: 7.6 inches (foldable), Cover display: 6.2 inches",
    display_type: "Foldable Dynamic AMOLED 2X",
    os: "Android 11",
    chipset: "Qualcomm Snapdragon 888",
    memory: "12GB RAM",
    main_camera: "Triple-camera setup",
    front_camera: "10 MP (cover camera), 4 MP (under-display camera)",
    battery: "4,400mAh",
  },
  {
    id: 28,
    name: "Xiaomi Mi 11",
    brand: "Xiaomi",
    price: "$699",
    color: ["Midnight Gray", "Horizon Blue", "Frost White"],
    image: "",
    display_size: "6.81 inches",
    display_type: "AMOLED",
    os: "MIUI 12 based on Android 11",
    chipset: "Qualcomm Snapdragon 888",
    memory: "8GB / 12GB RAM",
    main_camera: "Triple-camera setup",
    front_camera: "20 MP",
    battery: "4,600mAh",
  },
  {
    id: 29,
    name: "Xiaomi Redmi Note 10 Pro",
    brand: "Xiaomi",
    price: "$279",
    color: ["Onyx Gray", "Glacier Blue", "Gradient Bronze"],
    image: "",
    display_size: "6.67 inches",
    display_type: "Super AMOLED",
    os: "MIUI 12 based on Android 11",
    chipset: "Qualcomm Snapdragon 732G",
    memory: "6GB / 8GB RAM",
    main_camera: "Quad-camera setup",
    front_camera: "16 MP",
    battery: "5,020mAh",
  },
  {
    id: 30,
    name: "Xiaomi Mi 10T Pro",
    brand: "Xiaomi",
    price: "$599",
    color: ["Cosmic Black", "Lunar Silver", "Aurora Blue"],
    image: "",
    display_size: "6.67 inches",
    display_type: "IPS LCD",
    os: "MIUI 12 based on Android 10",
    chipset: "Qualcomm Snapdragon 865",
    memory: "8GB RAM",
    main_camera: "Triple-camera setup",
    front_camera: "20 MP",
    battery: "5,000mAh",
  },
  {
    id: 31,
    name: "Xiaomi Poco X3 Pro",
    brand: "Xiaomi",
    price: "$249",
    color: ["Phantom Black", "Frost Blue", "Metal Bronze"],
    image: "",
    display_size: "6.67 inches",
    display_type: "IPS LCD",
    os: "MIUI 12 based on Android 11",
    chipset: "Qualcomm Snapdragon 860",
    memory: "6GB / 8GB RAM",
    main_camera: "Quad-camera setup",
    front_camera: "20 MP",
    battery: "5,160mAh",
  },
  {
    name: "Xiaomi Mi 11 Lite",
    brand: "Xiaomi",
    price: "$299",
    color: ["Boba Black", "Peach Pink", "Bubblegum Blue"],
    image: "",
    display_size: "6.55 inches",
    display_type: "AMOLED",
    os: "MIUI 12 based on Android 11",
    chipset: "Qualcomm Snapdragon 732G",
    memory: "6GB / 8GB RAM",
    main_camera: "Triple-camera setup",
    front_camera: "16 MP",
    battery: null,
  },
  {
    name: "Xiaomi Redmi Note 9 Pro",
    brand: "Xiaomi",
    price: "$249",
    color: ["Interstellar Gray", "Tropical Green", "Glacier White"],
    image: "",
    display_size: "6.67 inches",
    display_type: "IPS LCD",
    os: "MIUI 11 based on Android 10",
    chipset: "Qualcomm Snapdragon 720G",
    memory: "6GB / 8GB RAM",
    main_camera: "Quad-camera setup",
    front_camera: "16 MP",
    battery: "5,020mAh",
  },
  {
    name: "Xiaomi Mi 10T Lite",
    brand: "Xiaomi",
    price: "$279",
    color: ["Atlantic Blue", "Pearl Gray", "Rose Gold Beach"],
    image: "",
    display_size: "6.67 inches",
    display_type: "IPS LCD",
    os: "MIUI 12 based on Android 10",
    chipset: "Qualcomm Snapdragon 750G",
    memory: "6GB / 8GB RAM",
    main_camera: "Quad-camera setup",
    front_camera: "16 MP",
    battery: "4,820mAh",
  },
  {
    name: "OPPO Find X3 Pro",
    brand: "Oppo",
    price: "$1,199",
    color: ["Gloss Black", "Blue", "White"],
    image: "",
    display_size: "6.7 inches",
    display_type: "AMOLED",
    os: "ColorOS 11.2 based on Android 11",
    chipset: "Qualcomm Snapdragon 888",
    memory: "12GB RAM",
    main_camera: "Quad-camera setup",
    front_camera: "32 MP",
    battery: "4,500mAh",
  },
  {
    name: "OPPO Reno6 Pro",
    brand: "Oppo",
    price: "$699",
    color: ["Aurora", "Stellar Black"],
    image: "",
    display_size: "6.55 inches",
    display_type: "AMOLED",
    os: "ColorOS 11.3 based on Android 11",
    chipset: "MediaTek Dimensity 1200",
    memory: "8GB / 12GB RAM",
    main_camera: "Quad-camera setup",
    front_camera: "32 MP",
    battery: "4,500mAh",
  },
  {
    name: "OPPO A74",
    brand: "Oppo",
    price: "$279",
    color: ["Prism Black", "Midnight Blue"],
    image: "",
    display_size: "6.43 inches",
    display_type: "AMOLED",
    os: "ColorOS 11 based on Android 11",
    chipset: "Qualcomm Snapdragon 662",
    memory: "6GB / 8GB RAM",
    main_camera: "Quad-camera setup",
    front_camera: "16 MP",
    battery: "5,000mAh",
  },
  {
    name: "OPPO A54",
    brand: "Oppo",
    price: "$199",
    color: ["Crystal Black", "Starry Blue"],
    image: "",
    display_size: "6.51 inches",
    display_type: "IPS LCD",
    os: "ColorOS 7.2 based on Android 10",
    chipset: "MediaTek Helio P35",
    memory: "4GB / 6GB RAM",
    main_camera: "Quad-camera setup",
    front_camera: "16 MP",
    battery: "5,000mAh",
  },
  {
    name: "OPPO Find X3 Neo",
    brand: "Oppo",
    price: "$999",
    color: ["Galactic Silver", "Starlight Black"],
    image: "",
    display_size: "6.55 inches",
    display_type: "AMOLED",
    os: "ColorOS 11.1 based on Android 11",
    chipset: "Qualcomm Snapdragon 865",
    memory: "12GB RAM",
    main_camera: "Quad-camera setup",
    front_camera: "32 MP",
    battery: "4,500mAh",
  },
  {
    name: "OPPO A15",
    brand: "Oppo",
    price: "$149",
    color: ["Dynamic Black", "Mystery Blue"],
    image: "",
    display_size: "6.52 inches",
    display_type: "IPS LCD",
    os: "ColorOS 7.2 based on Android 10",
    chipset: "MediaTek Helio P35",
    memory: "2GB / 3GB RAM",
    main_camera: "Triple-camera setup",
    front_camera: "5 MP",
    battery: "4,230mAh",
  },
  {
    name: "OPPO Reno5 Pro+",
    brand: "Oppo",
    price: "$799",
    color: ["Starry Night Black", "Fantasy Silver"],
    image: "",
    display_size: "6.55 inches",
    display_type: "AMOLED",
    os: "ColorOS 11 based on Android 11",
    chipset: "Qualcomm Snapdragon 865",
    memory: "8GB / 12GB RAM",
    main_camera: "Quad-camera setup",
    front_camera: "32 MP",
    battery: "4,500mAh",
  },
  {
    name: "Nokia X20",
    brand: "Nokia",
    price: "$399",
    color: ["Midnight Sun", "Nordic Blue"],
    image: "",
    display_size: "6.67 inches",
    display_type: "IPS LCD",
    os: "Android 11",
    chipset: "Qualcomm Snapdragon 480 5G",
    memory: "6GB / 8GB RAM",
    main_camera: "Quad-camera setup",
    front_camera: "32 MP",
    battery: "4,470mAh",
  },
  {
    name: "Nokia 8.3 5G",
    brand: "Nokia",
    price: "$599",
    color: ["Polar Night"],
    image: "",
    display_size: "6.81 inches",
    display_type: "IPS LCD",
    os: "Android 11",
    chipset: "Qualcomm Snapdragon 765G",
    memory: "6GB / 8GB RAM",
    main_camera: "Quad-camera setup",
    front_camera: "24 MP",
    battery: "4,500mAh",
  },
  {
    name: "Nokia G10",
    brand: "Nokia",
    price: "$149",
    color: ["Night", "Dusk"],
    image: "",
    display_size: "6.52 inches",
    display_type: "IPS LCD",
    os: "Android 11",
    chipset: "MediaTek Helio G25",
    memory: "3GB / 4GB RAM",
    main_camera: "Triple-camera setup",
    front_camera: "8 MP",
    battery: "5,050mAh",
  },
  {
    name: "Nokia 5.4",
    brand: "Nokia",
    price: "$249",
    color: ["Polar Night", "Dusk"],
    image: "",
    display_size: "6.39 inches",
    display_type: "IPS LCD",
    os: "Android 11",
    chipset: "Qualcomm Snapdragon 662",
    memory: "4GB / 6GB RAM",
    main_camera: "Quad-camera setup",
    front_camera: "16 MP",
    battery: "4,000mAh",
  },
  {
    name: "Nokia C20",
    brand: "Nokia",
    price: "$99",
    color: ["Sand", "Dark Blue"],
    image: "",
    display_size: "6.52 inches",
    display_type: "IPS LCD",
    os: "Android 11 (Go edition)",
    chipset: "Unisoc SC9863A",
    memory: "1GB / 2GB RAM",
    main_camera: "Single-camera",
    front_camera: "5 MP",
    battery: "3,000mAh",
  },
  {
    name: "Nokia XR20",
    brand: "Nokia",
    price: "$549",
    color: ["Ultra Blue", "Granite Gray"],
    image: "",
    display_size: "6.67 inches",
    display_type: "IPS LCD",
    os: "Android 11",
    chipset: "Qualcomm Snapdragon 480 5G",
    memory: "4GB / 6GB RAM",
    main_camera: "Dual-camera setup",
    front_camera: "8 MP",
    battery: "4,630mAh",
  },
  {
    name: "Nokia 3.4",
    brand: "Nokia",
    price: "$179",
    color: ["Fjord", "Dusk", "Charcoal"],
    image: "",
    display_size: "6.39 inches",
    display_type: "IPS LCD",
    os: "Android 11",
    chipset: "Qualcomm Snapdragon 460",
    memory: "3GB / 4GB RAM",
    main_camera: "Triple-camera setup",
    front_camera: "8 MP",
    battery: "4,000mAh",
  },
];
